version: '3.8'

services:
  bot:
    build: .
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/your_db
      - DB_USER=postgres
      - DB_PASSWORD=tgbot

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
