package alafonin4.TolikBot.Entity;

public enum Stage {
    EnterFirstName,
    EnterNameOfItemToDelete,
    EnterNameOfItemToAdd,
    EnterShopOfItemToAdd,
    EnterCountOfItemToAdd,
    CheckingInviting,
    EnterUserNameOfFriend,
    AskingQuestion,
    AnsweringQuestion,
    EnterReasonManually,
    EnterReasonManuallyToReview,
    EnterImageOrder,
    EnterNewAdminUser,
    EnterDeletingAdminUser,
    EnterNewModeratorUser,
    EnterDeletingModeratorUser,
    EnterImageReview,
    ChangingStatInItem,
    DoingNothing,
    EnterCostOfItem,
    ChangingList,
    EnterToAddToRes,
    EnterToSubToRes,
    EnterUrlOfItemToAdd,
    EnterCountOfStarsFromReview,

}
